# all available settings of specific linters
linters-settings:
  gofmt:
    simplify: true
  gofumpt:
    simplify: true
  goimports:
    local-prefixes: github.com/GetStream/stream-chat-go
  errcheck:
    check-type-assertions: false
    check-blank: false
  gocritic:
    disabled-checks:
      - unnamedResult
      - whyNoLint
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    settings:
      hugeParam:
        sizeThreshold: 377
      rangeValCopy:
        sizeThreshold: 364
        skipTestFuncs: true
  govet:
    enable-all: true
    disable:
      - shadow
run:
  skip-dirs:
    - hack
  tests: true

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - dogsled
    - dupl
    - errcheck
    - gci
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goimports
    - golint
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - prealloc
    - staticcheck
    - structcheck
    - unconvert
    - unparam
    - unused
    - varcheck
issues:
  exclude:
    - 'G404:' # math/rand usage
