# all available settings of specific linters
linters-settings:
  gofmt:
    simplify: true
  gofumpt:
    simplify: true
  goimports:
    local-prefixes: github.com/GetStream/stream-chat-go
  errcheck:
    check-type-assertions: false
    check-blank: false
  gocritic:
    disabled-checks:
      - unnamedResult
      - whyNoLint
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    settings:
      hugeParam:
        sizeThreshold: 512
      rangeValCopy:
        sizeThreshold: 364
        skipTestFuncs: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
run:
  skip-dirs:
    - hack
  tests: true

linters:
  enable-all: true
  disable:
    - contextcheck
    - exhaustivestruct
    - exhaustruct
    - funlen
    - gochecknoglobals
    - godox
    - goerr113
    - golint
    - gomnd
    - interfacer
    - lll
    - maligned
    - nlreturn
    - nonamedreturns
    - paralleltest
    - scopelint
    - tagliatelle
    - thelper
    - varnamelen
    - wrapcheck
    - wsl
issues:
  exclude-rules:
    - linters:
        - stylecheck
      text: 'ST1003:' # should not use underscores in package names
    - linters:
        - revive
      text: "don't use an underscore in package name"
    - linters:
        - gocritic
      text: 'commentFormatting'
    - path: _test\.go
      linters:
        - gosec
        - testpackage # makes you use a separate _test package
