name: build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test-build:
    name: Test & Build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        goVer: [1.16, 1.17]
    steps:
      - name: Set up Go ${{ matrix.goVer }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.goVer }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test via ${{ matrix.goVer }}
        env:
          STREAM_CHAT_API_KEY: ${{ secrets.STREAM_CHAT_API_KEY }}
          STREAM_CHAT_API_SECRET: ${{ secrets.STREAM_CHAT_API_SECRET }}
        run: go test -v -race ./...

      - name: Build on ${{ matrix.goVer }}
        run: go build ./...
